# Generated by Django 4.1.4 on 2022-12-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rested', models.PositiveSmallIntegerField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
