# Generated by Django 4.1.4 on 2022-12-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CharWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completed', models.BooleanField()),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_ark_checklist.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_ark_checklist.user'),
        ),
        migrations.AddField(
            model_name='chardaily',
            name='char_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lost_ark_checklist.character'),
            preserve_default=False,
        ),
    ]
