# Generated by Django 4.1.4 on 2022-12-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0002_character_user_charweekly_character_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='chardaily',
            old_name='char_id',
            new_name='char',
        ),
        migrations.RenameField(
            model_name='charweekly',
            old_name='char_id',
            new_name='char',
        ),
    ]
