# Generated by Django 4.1.4 on 2023-01-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0004_rosterweekly_rosterdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
