# Generated by Django 4.1.4 on 2023-01-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0006_alter_user_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
