# Generated by Django 4.1.4 on 2023-01-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0007_alter_user_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chardaily',
            name='img_path',
            field=models.FilePathField(default=1),
            preserve_default=False,
        ),
    ]
