# Generated by Django 4.1.4 on 2023-01-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0008_chardaily_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chardaily',
            name='img_path',
            field=models.FilePathField(verbose_name='/static/lost_ark_checklist/img'),
        ),
    ]
