# Generated by Django 4.1.4 on 2023-01-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0009_alter_chardaily_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chardaily',
            name='img_path',
        ),
    ]
