# Generated by Django 4.1.4 on 2023-01-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0010_remove_chardaily_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='chardaily',
            name='img_path',
            field=models.FilePathField(default=1, verbose_name='/static/lost_ark_checklist/img/donation.png'),
            preserve_default=False,
        ),
    ]
