# Generated by Django 4.1.4 on 2023-01-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0013_alter_chardaily_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chardaily',
            name='img_path',
            field=models.FilePathField(path='/static/lost_ark_checklist/img/donation.png'),
        ),
    ]
