# Generated by Django 4.1.4 on 2023-01-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0017_alter_chardaily_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chardaily',
            name='img_path',
        ),
        migrations.AddField(
            model_name='chardaily',
            name='img_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
