# Generated by Django 4.1.4 on 2023-01-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0019_defaultrosteritem_alter_chardaily_rested'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultrosteritem',
            name='completed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='defaultrosteritem',
            name='item_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], max_length=6),
        ),
    ]
