# Generated by Django 4.1.4 on 2023-01-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0021_defaultrosteritem_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultRosterItem',
        ),
    ]
