# Generated by Django 4.1.4 on 2023-01-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_ark_checklist', '0022_delete_defaultrosteritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='charweekly',
            name='img_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='rosterdaily',
            name='img_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='rosterweekly',
            name='img_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='chardaily',
            name='img_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
